import { createContext, useContext, useMemo, useReducer, type ReactNode } from "react";
import type { AppState, GroupToast, Session, SurfaceId, SettingsState } from "./types";
import { demoState } from "../fixtures/demo";

/**
 * `live.local.ts` is generated by `npm run snapshot` from this machine's real
 * Claude Code state and is gitignored. When absent — every clone but this one
 * — the glob resolves empty and the app runs on synthetic data.
 */
const liveModules = import.meta.glob<{ liveState: AppState; liveMeta: Record<string, number> }>(
  "../fixtures/live.local.ts",
  { eager: true },
);
const liveEntry = Object.values(liveModules)[0];
export const liveState: AppState | null = liveEntry?.liveState ?? null;
export const liveMeta: Record<string, number> | null = liveEntry?.liveMeta ?? null;
export const hasLive = liveState !== null;

/** UI state. Distinct from AppState, which the real app will source from core. */
export interface UiState {
  source: "demo" | "live";
  surface: SurfaceId;
  activeGroupId: string;
  /** Active session per column. */
  activeByColumn: Record<string, string>;
  /** Group opened full-screen as a focused plane. */
  focusMode: boolean;
  paletteOpen: boolean;
  windDownOpen: boolean;
  newSessionOpen: boolean;
  dayPromptOpen: boolean;
  brainTab: "lobe" | "vault";
  toasts: GroupToast[];
  /** null = broadcast to every session. */
  promptTarget: string | null;
  promptText: string;
  dictating: boolean;
  inspectorNodeId: string | null;
  settingsTab: string;
  docsTopic: string;
}

export interface Store {
  app: AppState;
  ui: UiState;
  dispatch: React.Dispatch<Action>;
}

export type Action =
  | { type: "surface"; id: SurfaceId }
  | { type: "group"; id: string }
  | { type: "activate"; columnId: string; sessionId: string }
  | { type: "closeSession"; sessionId: string }
  | { type: "moveSession"; sessionId: string; columnId: string; groupId?: string }
  | { type: "newSession"; groupId: string; incognito: boolean; runtime: "claude" | "codex"; title: string }
  | { type: "renameSession"; sessionId: string; title: string }
  | { type: "focus"; on: boolean }
  | { type: "palette"; open: boolean }
  | { type: "windDown"; open: boolean }
  | { type: "newSessionModal"; open: boolean }
  | { type: "dayPrompt"; open: boolean }
  | { type: "setObjective"; text: string }
  | { type: "brainTab"; tab: "lobe" | "vault" }
  | { type: "promptTarget"; id: string | null }
  | { type: "promptText"; text: string }
  | { type: "sendPrompt" }
  | { type: "dictate"; on: boolean }
  | { type: "dismissToast"; id: string }
  | { type: "undoGrouping"; id: string }
  | { type: "inspect"; id: string | null }
  | { type: "settingsTab"; tab: string }
  | { type: "docsTopic"; topic: string }
  | { type: "settings"; patch: Partial<SettingsState> }
  | { type: "addGroup"; name: string; root: string }
  | { type: "renameGroup"; id: string; name: string }
  | { type: "deleteGroup"; id: string }
  | { type: "toggleTask"; taskId: string }
  | { type: "windDownAll" }
  | { type: "resumeAll" }
  | { type: "source"; source: "demo" | "live" };

const uid = () => Math.random().toString(36).slice(2, 10);

function reduce(state: { app: AppState; ui: UiState }, a: Action): { app: AppState; ui: UiState } {
  const { app, ui } = state;
  switch (a.type) {
    case "surface":
      return { app, ui: { ...ui, surface: a.id, focusMode: a.id === "groups" ? ui.focusMode : false } };
    case "group":
      return { app, ui: { ...ui, activeGroupId: a.id, surface: "groups" } };
    case "activate":
      return { app, ui: { ...ui, activeByColumn: { ...ui.activeByColumn, [a.columnId]: a.sessionId }, promptTarget: a.sessionId } };
    case "closeSession": {
      const sessions = app.sessions.filter((s) => s.id !== a.sessionId);
      return { app: { ...app, sessions }, ui: { ...ui, promptTarget: ui.promptTarget === a.sessionId ? null : ui.promptTarget } };
    }
    case "moveSession": {
      const sessions = app.sessions.map((s) =>
        s.id === a.sessionId
          ? { ...s, columnId: a.columnId, groupId: a.groupId ?? s.groupId, pinnedToGroup: a.groupId ? true : s.pinnedToGroup }
          : s,
      );
      return { app: { ...app, sessions }, ui };
    }
    case "newSession": {
      const group = app.groups.find((g) => g.id === a.groupId);
      const cols = app.sessions.filter((s) => s.groupId === a.groupId).map((s) => s.columnId);
      const columnId = cols[0] ?? `c-${uid()}`;
      const id = crypto.randomUUID();
      const now = new Date().toISOString();
      const s: Session = {
        id, shortId: id.slice(0, 8), title: a.title || (a.incognito ? "Incognito session" : "New session"),
        groupId: a.groupId, runtime: a.runtime,
        model: a.runtime === "codex" ? "gpt-5-codex" : app.settings.model,
        status: "idle", tier: 1, cwd: group?.primaryRoot ?? "~", gitBranch: null,
        startedAt: now, lastActivityAt: now,
        tokens: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
        costEstimateUsd: 0, incognito: a.incognito, remoteControlled: false, entrypoint: "abcd",
        pinnedToGroup: true, outsideRoot: false, linearRefs: [], columnId,
      };
      return {
        app: { ...app, sessions: [s, ...app.sessions] },
        ui: { ...ui, newSessionOpen: false, surface: "groups", activeGroupId: a.groupId, promptTarget: id, activeByColumn: { ...ui.activeByColumn, [columnId]: id } },
      };
    }
    case "renameSession":
      return { app: { ...app, sessions: app.sessions.map((s) => (s.id === a.sessionId ? { ...s, title: a.title } : s)) }, ui };
    case "focus":
      return { app, ui: { ...ui, focusMode: a.on } };
    case "palette":
      return { app, ui: { ...ui, paletteOpen: a.open } };
    case "windDown":
      return { app, ui: { ...ui, windDownOpen: a.open } };
    case "newSessionModal":
      return { app, ui: { ...ui, newSessionOpen: a.open } };
    case "dayPrompt":
      return { app, ui: { ...ui, dayPromptOpen: a.open } };
    case "setObjective":
      return { app: { ...app, today: { ...app.today, text: a.text } }, ui: { ...ui, dayPromptOpen: false } };
    case "brainTab":
      return { app, ui: { ...ui, brainTab: a.tab } };
    case "promptTarget":
      return { app, ui: { ...ui, promptTarget: a.id } };
    case "promptText":
      return { app, ui: { ...ui, promptText: a.text } };
    case "sendPrompt": {
      const text = ui.promptText.trim();
      if (!text) return state;
      const targets = ui.promptTarget ? [ui.promptTarget] : app.sessions.map((s) => s.id);
      const now = new Date().toISOString();
      const newTurns = targets.map((sid) => ({ id: uid(), sessionId: sid, role: "user" as const, at: now, text }));
      const sessions = app.sessions.map((s) =>
        targets.includes(s.id) && s.tier !== 3 ? { ...s, status: "working" as const, lastActivityAt: now } : s,
      );
      return { app: { ...app, turns: [...app.turns, ...newTurns], sessions }, ui: { ...ui, promptText: "" } };
    }
    case "dictate":
      return { app, ui: { ...ui, dictating: a.on } };
    case "dismissToast":
      return { app, ui: { ...ui, toasts: ui.toasts.filter((t) => t.id !== a.id) } };
    case "undoGrouping": {
      const toast = ui.toasts.find((t) => t.id === a.id);
      if (!toast) return state;
      // Undo pins the session so re-inference never overrides the human. Decision 13.
      const sessions = app.sessions.map((s) => (s.id === toast.sessionId ? { ...s, pinnedToGroup: true } : s));
      return { app: { ...app, sessions }, ui: { ...ui, toasts: ui.toasts.filter((t) => t.id !== a.id) } };
    }
    case "inspect":
      return { app, ui: { ...ui, inspectorNodeId: a.id } };
    case "settingsTab":
      return { app, ui: { ...ui, settingsTab: a.tab } };
    case "docsTopic":
      return { app, ui: { ...ui, docsTopic: a.topic } };
    case "settings":
      return { app: { ...app, settings: { ...app.settings, ...a.patch } }, ui };
    case "addGroup": {
      const g = { id: `g-${uid()}`, name: a.name, primaryRoot: a.root, extraRoots: [], glyphSeed: a.name, order: app.groups.length };
      return { app: { ...app, groups: [...app.groups, g] }, ui: { ...ui, activeGroupId: g.id } };
    }
    case "renameGroup":
      return { app: { ...app, groups: app.groups.map((g) => (g.id === a.id ? { ...g, name: a.name } : g)) }, ui };
    case "deleteGroup": {
      const groups = app.groups.filter((g) => g.id !== a.id);
      const sessions = app.sessions.filter((s) => s.groupId !== a.id);
      const next = groups[0]?.id ?? "";
      return { app: { ...app, groups, sessions }, ui: { ...ui, activeGroupId: ui.activeGroupId === a.id ? next : ui.activeGroupId } };
    }
    case "toggleTask": {
      const tasks = app.tasks.map((t) =>
        t.id === a.taskId ? { ...t, status: t.status === "completed" ? ("pending" as const) : ("completed" as const) } : t,
      );
      return { app: { ...app, tasks }, ui };
    }
    case "windDownAll": {
      const sessions = app.sessions.map((s) => (s.tier === 3 ? s : { ...s, status: "idle" as const }));
      return { app: { ...app, sessions }, ui: { ...ui, windDownOpen: false } };
    }
    case "resumeAll": {
      const sessions = app.sessions.map((s) => (s.status === "idle" && s.tier !== 3 ? { ...s, status: "working" as const } : s));
      return { app: { ...app, sessions }, ui };
    }
    case "source": {
      const next = a.source === "live" && liveState ? liveState : demoState;
      return { app: next, ui: { ...initialUiFor(next), source: a.source === "live" && liveState ? "live" : "demo", surface: ui.surface } };
    }
    default:
      return state;
  }
}

function initialUiFor(state: AppState): UiState {
  const activeByColumn: Record<string, string> = {};
  for (const s of state.sessions) if (!activeByColumn[s.columnId]) activeByColumn[s.columnId] = s.id;
  const first =
    state.sessions.find((s) => s.status === "working") ??
    state.sessions.find((s) => s.status === "needs-input") ??
    state.sessions[0];
  return {
    source: state.demo ? "demo" : "live",
    surface: "home",
    activeGroupId: first?.groupId ?? state.groups[0]?.id ?? "",
    activeByColumn,
    focusMode: false,
    paletteOpen: false,
    windDownOpen: false,
    newSessionOpen: false,
    dayPromptOpen: false,
    brainTab: "lobe",
    toasts: first
      ? [{ id: "toast-1", sessionId: first.id, sessionTitle: first.title, toGroupId: first.groupId, at: Date.now() }]
      : [],
    promptTarget: first?.id ?? null,
    promptText: "",
    dictating: false,
    inspectorNodeId: null,
    settingsTab: "appearance",
    docsTopic: "start",
  };
}

// Boot straight into real data when a snapshot exists on this machine.
const bootState: AppState = liveState ?? demoState;

const Ctx = createContext<Store | null>(null);

export function StoreProvider({ children }: { children: ReactNode }) {
  const [state, dispatch] = useReducer(reduce, { app: bootState, ui: initialUiFor(bootState) });
  const value = useMemo(() => ({ app: state.app, ui: state.ui, dispatch }), [state]);
  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}

export function useStore(): Store {
  const v = useContext(Ctx);
  if (!v) throw new Error("useStore must be used inside StoreProvider");
  return v;
}

/** Sessions of a group, split into their columns, in column order. */
export function useColumns(groupId: string) {
  const { app } = useStore();
  return useMemo(() => {
    const inGroup = app.sessions.filter((s) => s.groupId === groupId);
    const ids = Array.from(new Set(inGroup.map((s) => s.columnId)));
    return ids.map((id) => ({ id, sessions: inGroup.filter((s) => s.columnId === id) }));
  }, [app.sessions, groupId]);
}
